package com.tttsaurus.rayoff.api.event.collision;

import com.tttsaurus.rayoff.api.PhysicsElement;
import com.tttsaurus.rayoff.impl.bullet.collision.body.ElementRigidBody;
import com.tttsaurus.rayoff.impl.bullet.collision.body.TerrainRigidBody;
import dev.lazurite.toolbox.api.event.Event;

/**
 * @since 1.0.0
 */
public class ElementCollisionEvents {
    public static final Event<BlockCollision> BLOCK_COLLISION = Event.create();
    public static final Event<BlockCollision> FLUID_COLLISION = Event.create();
    public static final Event<ElementCollision> ELEMENT_COLLISION = Event.create();

    private ElementCollisionEvents() { }

    @FunctionalInterface
    public interface BlockCollision {
        /**
         * Invoked each time an {@link ElementRigidBody} collides with a {@link }.
         * @param element the element
         * @param terrainObject the terrain object
         * @param impulse the impulse generated by the collision
         */
        void onCollide(PhysicsElement element, TerrainRigidBody terrainObject, float impulse);
    }

    @FunctionalInterface
    public interface FluidCollision {
        /**
         * Invoked each time an {@link ElementRigidBody} collides with a {@link TerrainRigidBody}.
         * @param element the element
         * @param terrainObject the terrain object
         * @param impulse the impulse generated by the collision
         */
        void onCollide(PhysicsElement element, TerrainRigidBody terrainObject, float impulse);
    }

    @FunctionalInterface
    public interface ElementCollision {
        /**
         * Invoked each time an {@link ElementRigidBody} collides with another {@link ElementRigidBody}.
         * @param element1 the first element
         * @param element2 the second element
         * @param impulse the impulse generated by the collision
         */
        void onCollide(PhysicsElement element1, PhysicsElement element2, float impulse);
    }
}
